LEFT, RIGHT, UP, DOWN, FIRE1, FIRE2 = 0, 1, 2, 3, 4, 5
BLACK, DARK_BLUE, DARK_PURPLE, DARK_GREEN, BROWN, DARK_GRAY, LIGHT_GRAY, WHITE, RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, PINK, PEACH =
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15

SCREEN_SIZE = 128
SCREEN_CENTER = SCREEN_SIZE / 2
FONT_WIDTH, FONT_HEIGHT = 4, 5
SPRITE_PLAYER = 240

_UPD, _DRW = NOOP, NOOP

function _init()
    _UPD = UPDATE_GAME
    _DRW = DRAW_GAME

    P_X, P_Y = 7, 6
end

function _update60() _UPD() end

function _draw() _DRW() end
